### ISSUE TITLE
Include today's prices by default

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/flexmeasures-entsoe#26]
At the time of querying ENTSO-E, not just tomorrow's prices are relevant, but also today's prices.

**Comment by Ahmad-Wahid** [comment]
If we don't pass `from-date` and `to-date`, then by default we will get today's and tomorrow's prices, right?

**Comment by nhoening** [comment]
I believe it's only tomorrow

**Comment by nhoening** [comment]
I believe it's only tomorrow

**Comment by Ahmad-Wahid** [comment]
Currently, it's only tomorrow, but we drop the extra day we add with `to-date`, then we can get today's and tomorrow's prices if it's available.
