### ISSUE TITLE
entsoe plug-in throws an error while creating bdf = BeliefsDataFrame(...

### ISSUE THREAD

**Issue by tnlrgn2** [SeitaBV/flexmeasures-entsoe#36]
Hi

I see an error when running the plugin (for day ahead prices and generation).

Run:  flexmeasures entsoe import-day-ahead-prices

Result:
[FLEXMEASURES] Task entsoe-import-day-ahead-prices encountered a problem: ""DataFrame should contain column named 'source'."". More details: {'src_module': '/usr/local/lib/python3.10/dist-packages/timely_beliefs/beliefs/classes.py', 'src_linenr': 910, 'src_func': '__init__', 'src_code': 'raise KeyError("DataFrame should contain column named \'source\'.")'}

This is happening with main repo: 41a89ad + Docker Image from the toy tutorial

**Comment by Ahmad-Wahid** [comment]
Hi @tnlrgn2, let me have a look.

**Comment by Ahmad-Wahid** [comment]
Can you tell me which `timely-beliefs` version you have?

**Comment by Ahmad-Wahid** [comment]
I have followed the tutorial, but I wasn't able to reproduce it on my machine.

**Comment by nhoening** [comment]
We are interested in reproducing this, though, because we saw this error happening in our FlexMeasures CI (Github Actions), but cannot reproduce on our dev laptops.

So all context information helps. 

What OS are you on?

What is the docker image version? (then we can also derermine timely beliefs and other versions)

**Comment by Ahmad-Wahid** [comment]
@tnlrgn2 I have answered this problem in #38.

**Comment by tnlrgn2** [comment]
Hi

Name: pandas
Version: 2.1.4

Name: entsoe-py
Version: 0.6.2

and latest flexmeasures docker container for tutorial + enstoe flexmeasures plugin v0.8 works as expected.

thanks.
