### ISSUE TITLE
Reading data from ENTSOE fails

### ISSUE THREAD

**Issue by rhpijnacker** [SeitaBV/flexmeasures-entsoe#38]
I am running command `flexmeasures entsoe import-day-ahead-prices`, which fails with the following error message:
```
[FLEXMEASURES][2024-05-04 14:24:46,595] INFO: Importing day-ahead price data for NL (timezone Europe/Amsterdam), starting at 2024-05-04 00:00:00+02:00, up until 2024-05-06 00:00:00+02:00, from ENTSO-E at https://web-api.tp.entsoe.eu/api ...
[FLEXMEASURES][2024-05-04 14:24:46,595] INFO: Getting prices ...
/usr/lib/python3.10/html/parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)
[FLEXMEASURES] Task entsoe-import-day-ahead-prices encountered a problem: "'Series' object has no attribute 'append'". More details: {'src_module': '/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py', 'src_linenr': 6204, 'src_func': '__getattr__', 'src_code': 'return object.__getattribute__(self, name)'}
```

**Comment by nhoening** [comment]
Probably related to #36.

We seem to have a hard time reproducing.
What is the docker image version and are you on the latest main?

**Comment by rhpijnacker** [comment]
I am using the latest of everything. (Brand new installation)

**Comment by Ahmad-Wahid** [comment]
Hello @rhpijnacker, I appreciate you bringing up the updated version of `entsoe-py`. Upon investigation, I've discovered that installing the latest version, `entsoe-py==0.6.7`, poses an issue as it installs `pandas==2.2.2`, which is currently incompatible with our plugin. It's advisable to install `entsoe-py<=0.6.2` instead. Hopefully, this adjustment will resolve your issue. 

Additionally, I'll make sure to update the ReadMe file accordingly.

**Comment by rhpijnacker** [comment]
Hi @Ahmad-Wahid,
Thanks for the investigation.
I can confirm that downgrading to entsoe 0.6.2 fixes the problems. Importing the day-ahead prices works now.

**Comment by nhoening** [comment]
Hi @tnlrgn2 we saw this (keeping pandas below 2.2.2) solving the same issue of others, so closing this.
Feel free to reopen or ask more questions, though.
