### ISSUE TITLE
Getting no data: NoMatchingDataError

### ISSUE THREAD

**Issue by rhpijnacker** [SeitaBV/flexmeasures-entsoe#41]
FlexMeasures has been running nice and stable for months now, but yesterday it suddenly can not get the entsoe data from the server. I'm getting this error:

```
[FLEXMEASURES][2024-08-30 04:45:27,397] INFO: Importing day-ahead price data for NL (timezone Europe/Amsterdam), starting at 2024-08-30 00:00:00+02:00, up until 2024-09-01 00:00:00+02:00, from ENTSO-E at https://web-api.tp.entsoe.eu/api ...
[FLEXMEASURES][2024-08-30 04:45:27,397] INFO: Getting prices ...
[FLEXMEASURES] Task entsoe-import-day-ahead-prices encountered a problem: "". More details: {'src_module': '/usr/local/lib/python3.10/dist-packages/entsoe/decorators.py', 'src_linenr': 145, 'src_func': 'year_wrapper', 'src_code': 'raise NoMatchingDataError'}
[FLEXMEASURES] Reported task entsoe-import-day-ahead-prices status as False
```

Any ideas what is going on?

**Comment by nhoening** [comment]
Well ENTSO-E sometimes is late with providing data. You can check in their transparency portal online if the data is actually available through them.

We have a second fallback cron job later in the day because it happens sometimes.

**Comment by rhpijnacker** [comment]
Looks like this was indeed the case.
Do you have a recommendation for what would be good times for fetching the data?

**Comment by Flix6x** [comment]
We haven't monitored Transparency's precise publication lags, but I recommend trying later in the afternoon (this already catches most delays), in the evening and just before midnight (when today's prices run out).

If you have a different source of the same prices (your energy supplier usually has them in their app), it should also be relatively straightforward to use the flexmeasures-client to enter the data by API yourself. Some energy suppliers offer their own APIs to fetch the prices, so there is some automation potential in that direction, too.

**Comment by rhpijnacker** [comment]
Thanks, Felix
