### ISSUE TITLE
Plugin incompatible with latest FlexMeasures server

### ISSUE THREAD

**Issue by rhpijnacker** [SeitaBV/flexmeasures-entsoe#44]
Updating my flexmeasures server from v0.20.0 to v0.21.0 or later gives me the following error:
```
[FLEXMEASURES][2024-10-02 19:02:54,148] INFO: Loading config from /usr/var/flexmeasures-instance/flexmeasures.cfg ...
[FLEXMEASURES][2024-10-02 19:02:54,157] INFO: [FLEXMEASURES] No SENTRY_DSN setting found, so initialising Sentry cannot happen ...
[FLEXMEASURES][2024-10-02 19:02:56,003] WARNING: `app.reporters` is deprecated. Use `app.data_generators["reporter"]` instead.
[FLEXMEASURES][2024-10-02 19:02:56,379] INFO: Importing plugin flexmeasures-entsoe ...
[FLEXMEASURES][2024-10-02 19:02:56,601] INFO: Loaded plugins: {'flexmeasures-entsoe': '0.8'}
[FLEXMEASURES][2024-10-02 19:02:56,720] INFO: Importing day-ahead price data for NL (timezone Europe/Amsterdam), starting at 2024-10-02 00:00:00+02:00, up until 2024-10-04 00:00:00+02:00, from ENTSO-E at https://web-api.tp.entsoe.eu/api ...
[FLEXMEASURES][2024-10-02 19:02:56,721] INFO: Getting prices ...
[FLEXMEASURES] Task entsoe-import-day-ahead-prices encountered a problem: "'60min'". More details: {'src_module': '/usr/local/lib/python3.10/dist-packages/entsoe/parsers.py', 'src_linenr': 38, 'src_func': 'parse_prices', 'src_code': 'series[soup_series.index.freqstr].append(soup_series)'}
[FLEXMEASURES] Reported task entsoe-import-day-ahead-prices status as False
```

**Comment by nhoening** [comment]
I can as of now only report that we run it with 0.22, and we haven't seen this there.

**Comment by rhpijnacker** [comment]
Oh, that is strange. I'm running the Docker from the docker registry and the pluin from github without any changes.
Could this be a dependency versioning issue? I noticed yesterday I was still using entsoe at 0.6.2, which is a bit outdated. 
Maybe there are other dependencies that are outdated without me being aware?

**Comment by rhpijnacker** [comment]
Just updated to server v0.22.0, entsoe-py 0.6.9, and github main of the plugin.
Everything appears to be working ok now.

**Comment by nhoening** [comment]
Great. Why not 0.23 though?

**Comment by rhpijnacker** [comment]
No particular reason. Since you mentioned 0.22 above, I just assumed this was the latest version.

**Comment by nhoening** [comment]
Ah okay.
The latest versions are visible here: https://pypi.org/project/flexmeasures/#history, and all commits per version here: https://github.com/FlexMeasures/flexmeasures/releases/tag/v0.23.0

But we also describe new releases in prose, here: https://flexmeasures.io/tags/blogpost/ (for instance, in 0.23 you might enjoy the new sensor page)
